<<<<<<< HEAD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: flask-container
        image: devops-k8s-app  # <-- Your locally built image
        imagePullPolicy: IfNotPresent  # <-- THIS FIXES THE ISSUE
        ports:
        - containerPort: 5000
=======
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
>>>>>>> master
